[package]
name = "awsb"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
copypasta = "0.10.1"
home = "0.5.9"
ini = "1.3.0"
regex = "1.11.1"
url = "2.5.2"
