pub enum Error {
    AWSCommandFailed,
    Aborted,
    AlreadyExists,
    ClashingURL,
    CouldNotCopyToClipboard,
    CouldNotEditConfigFile,
    CouldNotReadConfigFile,
    HomeDirectoryNotFound,
    InvalidAccountID,
    InvalidItem,
    InvalidName,
    InvalidRegion,
    InvalidUrl,
    NotFound,
    ProviderNotFound,
}
